name: Test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt -y install shellcheck
    - name: Run ShellCheck
      run: |
        shellcheck -V
        shellcheck -x bin/*.bash
